package_rename_config:
  android:
    app_name: "Your App"
    package_name: "com.example.yourapp"
    override_old_package: "com.example.mobile_template"
    lang: "kotlin"

  ios:
    app_name: "Your App"
    bundle_name: "Your App"
    package_name: "com.example.yourapp"
